--------------------------------------------------------
-- Archivo creado  - martes-marzo-11-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLEADOS
--------------------------------------------------------

  CREATE TABLE "GETAFESQL"."EMPLEADOS" 
   (	"ID" NUMBER(5,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"EDAD" NUMBER(3,0), 
	"SALARIO" NUMBER(10,2), 
	"DEPARTAMENTO_ID" NUMBER(3,0), 
	"FECHA_CONTRATACION" DATE DEFAULT SYSDATE, 
	"ID_EQUIPO" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into GETAFESQL.EMPLEADOS
SET DEFINE OFF;
Insert into GETAFESQL.EMPLEADOS (ID,NOMBRE,EDAD,SALARIO,DEPARTAMENTO_ID,FECHA_CONTRATACION,ID_EQUIPO) values ('3','Ana García','29','3360','1',to_date('04/03/25','DD/MM/RR'),'2');
Insert into GETAFESQL.EMPLEADOS (ID,NOMBRE,EDAD,SALARIO,DEPARTAMENTO_ID,FECHA_CONTRATACION,ID_EQUIPO) values ('4','Carlos Gómez','41','5100','2',to_date('04/01/25','DD/MM/RR'),'1');
Insert into GETAFESQL.EMPLEADOS (ID,NOMBRE,EDAD,SALARIO,DEPARTAMENTO_ID,FECHA_CONTRATACION,ID_EQUIPO) values ('6','Juan Pérez','31','3465','1',to_date('04/03/24','DD/MM/RR'),'1');
Insert into GETAFESQL.EMPLEADOS (ID,NOMBRE,EDAD,SALARIO,DEPARTAMENTO_ID,FECHA_CONTRATACION,ID_EQUIPO) values ('7','Ana García','28','3200','1',to_date('04/03/25','DD/MM/RR'),'2');
Insert into GETAFESQL.EMPLEADOS (ID,NOMBRE,EDAD,SALARIO,DEPARTAMENTO_ID,FECHA_CONTRATACION,ID_EQUIPO) values ('8','Carlos Gómez','40','5000','1',to_date('04/02/20','DD/MM/RR'),'1');
Insert into GETAFESQL.EMPLEADOS (ID,NOMBRE,EDAD,SALARIO,DEPARTAMENTO_ID,FECHA_CONTRATACION,ID_EQUIPO) values ('9','Laura Torres','25','2800,47','2',to_date('04/03/25','DD/MM/RR'),'2');
Insert into GETAFESQL.EMPLEADOS (ID,NOMBRE,EDAD,SALARIO,DEPARTAMENTO_ID,FECHA_CONTRATACION,ID_EQUIPO) values ('10','Juan Pérez','30','3000','3',to_date('04/03/25','DD/MM/RR'),'2');
--------------------------------------------------------
--  DDL for Index PK_EMPLEADOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "GETAFESQL"."PK_EMPLEADOS" ON "GETAFESQL"."EMPLEADOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table EMPLEADOS
--------------------------------------------------------

  ALTER TABLE "GETAFESQL"."EMPLEADOS" ADD CONSTRAINT "CHK_SALARIO" CHECK (salario > 0) ENABLE;
  ALTER TABLE "GETAFESQL"."EMPLEADOS" ADD CONSTRAINT "NOTNULL_NOMBRE" CHECK (nombre is not null) ENABLE;
  ALTER TABLE "GETAFESQL"."EMPLEADOS" ADD CONSTRAINT "PK_EMPLEADOS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLEADOS
--------------------------------------------------------

  ALTER TABLE "GETAFESQL"."EMPLEADOS" ADD CONSTRAINT "FK_EQUIPO" FOREIGN KEY ("ID_EQUIPO")
	  REFERENCES "GETAFESQL"."EQUIPOS" ("ID") ENABLE;
