-- 1. Crear la tabla usuarios con las columnas indicadas
CREATE TABLE usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    fecha_registro DATE DEFAULT SYSDATE
);

SELECT SYSDATE from dual;

-- 2. Modificar la tabla para añadir la columna "telefono"
ALTER TABLE usuarios
ADD (telefono VARCHAR2(15));

-- 3. Modificar el tipo de datos de la columna "nombre" a VARCHAR2(100)
ALTER TABLE usuarios
MODIFY (nombre VARCHAR2(100) NOT NULL);